changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - semver:major
    - title: Features
      labels:
        - type:feature
        - semver:minor
    - title: Fixes
      labels:
        - type:fix
        - bug
        - semver:patch
    - title: Security
      labels:
        - type:security
    - title: Documentation
      labels:
        - documentation
        - type:docs
    - title: Maintenance
      labels:
        - type:chore
        - dependencies
    - title: Other changes
      labels:
        - "*"

