/**
 * Audit Writer Repository (DUA-178).
 *
 * Writes append-only audit records to the audit_log table. The columns ARE
 * the whitelist — no query text, request bodies, payloads, or keys are ever
 * accepted or stored. The @teamem/schema auditItem.strictObject contract
 * prevents any extra field from reaching the database.
 *
 * Design invariants (N7):
 * - The write function signature accepts ONLY whitelisted fields (the schema
 *   IS the whitelist). Callers cannot accidentally pass sensitive content.
 * - For event.payload_read: fail-closed — an audit write failure MUST deny
 *   the payload read. The wrapper throws AuditWriteFailedError, and callers
 *   must not return payload data when this error is caught.
 * - Audit writes are append-only. The table has no FK constraints by design:
 *   rows survive purge, ids may dangle, and a write must never fail on
 *   referential grounds.
 * - auditId and createdAt are auto-generated by the database (UUID default +
 *   DEFAULT NOW()); the caller provides the remaining whitelisted fields.
 */
import { createHash, randomUUID } from 'node:crypto';
import { and, eq, lt, or, sql } from 'drizzle-orm';
import {
  auditItem,
  decodeCursor,
  encodeCursor,
  type AuditItem,
  type CursorPayload,
} from '@teamem/schema';
import * as schema from '../../db/schema.js';
import type { AppDb } from '../../db/client.js';

// ── Error types ─────────────────────────────────────────────────────────────

/**
 * Thrown when an audit write fails during a sensitive read (e.g. payload read).
 * Callers MUST treat this as a denial: do not return the requested data.
 */
export class AuditWriteFailedError extends Error {
  readonly name = 'AuditWriteFailedError';
}

// ── Whitelisted write parameters ────────────────────────────────────────────

/**
 * The exact set of fields that may be written to the audit log.
 *
 * This type IS the whitelist. No other fields exist here — callers cannot
 * pass query text, request bodies, payloads, or keys because the type
 * system won't allow it. The runtime validation via auditItem.strictObject
 * provides a second line of defense against any bypass.
 */
export interface AuditWriteParams {
  readonly requestId: string;
  readonly principalId: string | null;
  readonly credentialId: string | null;
  readonly action: string; // open registry — server writes only KNOWN_AUDIT_ACTIONS
  readonly resourceType: AuditItem['resourceType'];
  readonly resourceId: string | null;
  readonly teamId: string;
  readonly projectId: string | null;
  readonly outcome: AuditItem['outcome'];
}

// ── Validation ──────────────────────────────────────────────────────────────

/**
 * Build the full AuditItem shape from caller-supplied fields plus
 * auto-generated id and createdAt. Validates against the frozen
 * auditItem.strictObject contract.
 *
 * Rejects any payload that contains extra fields beyond the whitelist.
 */
function buildAuditRow(params: AuditWriteParams): AuditItem {
  const now = new Date();
  const id = randomUUID();

  const row = {
    id,
    createdAt: now.toISOString(),
    requestId: params.requestId,
    principalId: params.principalId,
    credentialId: params.credentialId,
    action: params.action,
    resourceType: params.resourceType,
    resourceId: params.resourceId,
    teamId: params.teamId,
    projectId: params.projectId,
    outcome: params.outcome,
  };

  // strictObject rejects any extra fields — the Zod schema IS the whitelist
  return auditItem.parse(row);
}

// ── Core write function ────────────────────────────────────────────────────

/**
 * Write a single audit record to the audit_log table.
 *
 * The input is validated against the frozen auditItem contract before
 * persistence. Extra fields (query text, payloads, keys, etc.) are
 * rejected at the Zod boundary.
 *
 * Returns the created AuditItem (including the generated id and createdAt).
 *
 * @param db - The Drizzle database instance
 * @param params - Whitelisted audit fields (see AuditWriteParams)
 * @returns The created AuditItem
 */
export async function writeAuditRecord(
  db: AppDb,
  params: AuditWriteParams,
): Promise<AuditItem> {
  const row = buildAuditRow(params);

  await db.insert(schema.auditLog).values({
    id: row.id,
    createdAt: new Date(row.createdAt),
    requestId: row.requestId,
    principalId: row.principalId,
    credentialId: row.credentialId,
    action: row.action,
    resourceType: row.resourceType,
    resourceId: row.resourceId,
    teamId: row.teamId,
    projectId: row.projectId,
    outcome: row.outcome,
  });

  return row;
}

// ── Fail-closed payload read helper ────────────────────────────────────────

/**
 * Parameters for the fail-closed payload-read audit wrapper.
 *
 * Narrower than AuditWriteParams: only the fields a payload-read caller
 * would legitimately possess. action, resourceType, and outcome are fixed
 * by the wrapper; resourceId is required (the event being read).
 */
export interface AuditPayloadReadParams {
  readonly requestId: string;
  readonly principalId: string | null;
  readonly credentialId: string | null;
  readonly teamId: string;
  readonly projectId: string | null;
  /** The event ID whose payload is being read. */
  readonly resourceId: string;
}

/**
 * Write an event.payload_read audit record. FAIL-CLOSED: if the audit
 * write fails for any reason, this function throws AuditWriteFailedError.
 *
 * Callers MUST catch this error and deny the payload read — the caller
 * must not return event payload data when this function throws.
 *
 * Usage pattern:
 * ```
 * await auditPayloadRead(db, { requestId, principalId, credentialId,
 *   teamId, projectId, resourceId: eventId });
 * // Only now return the payload — if the above threw, the read is denied.
 * ```
 *
 * @param db - The Drizzle database instance
 * @param params - Context fields for the audit record
 * @throws AuditWriteFailedError if the audit write fails (fail-closed)
 */
export async function auditPayloadRead(
  db: AppDb,
  params: AuditPayloadReadParams,
): Promise<void> {
  try {
    await writeAuditRecord(db, {
      requestId: params.requestId,
      principalId: params.principalId,
      credentialId: params.credentialId,
      action: 'event.payload_read',
      resourceType: 'event',
      resourceId: params.resourceId,
      teamId: params.teamId,
      projectId: params.projectId,
      outcome: 'success',
    });
  } catch (err) {
    // Fail closed: do not return the payload
    throw new AuditWriteFailedError(
      'Audit write failed; payload read denied',
      { cause: err },
    );
  }
}

// ── Audit read functions ────────────────────────────────────────────────────

/**
 * Full audit row as returned by read-side queries.
 */
export interface AuditRow {
  readonly id: string;
  readonly createdAt: Date;
  readonly requestId: string;
  readonly principalId: string | null;
  readonly credentialId: string | null;
  readonly action: string;
  readonly resourceType: AuditItem['resourceType'];
  readonly resourceId: string | null;
  readonly teamId: string;
  readonly projectId: string | null;
  readonly outcome: AuditItem['outcome'];
}

// Column selection matching the whitelist.
const AUDIT_COLUMNS = {
  id: schema.auditLog.id,
  createdAt: schema.auditLog.createdAt,
  requestId: schema.auditLog.requestId,
  principalId: schema.auditLog.principalId,
  credentialId: schema.auditLog.credentialId,
  action: schema.auditLog.action,
  resourceType: schema.auditLog.resourceType,
  resourceId: schema.auditLog.resourceId,
  teamId: schema.auditLog.teamId,
  projectId: schema.auditLog.projectId,
  outcome: schema.auditLog.outcome,
};

/**
 * Parameters for a cursor-paginated audit list query.
 * Sort: created_at DESC, id DESC (N8).
 */
export interface ListAuditParams {
  readonly teamId: string;
  readonly projectId?: string;
  readonly actor?: string;
  readonly action?: string;
  readonly cursor?: string;
  readonly limit: number;
}

/** Result of a list-audit query. */
export interface ListAuditResult {
  readonly rows: AuditRow[];
  readonly nextCursor: string | null;
}

/** Compute a stable hash of the list filters so the cursor can detect
 *  a changed filter set and reject the stale cursor (N3). */
function computeAuditFilterHash(params: {
  projectId?: string;
  actor?: string;
  action?: string;
}): string {
  const normalized: Record<string, string> = {};
  if (params.projectId) normalized['projectId'] = params.projectId;
  if (params.actor) normalized['actor'] = params.actor;
  if (params.action) normalized['action'] = params.action;
  return createHash('sha256')
    .update(JSON.stringify(normalized, Object.keys(normalized).sort()))
    .digest('hex')
    .slice(0, 16);
}

/**
 * List audit records with cursor-based pagination, ordered by
 * created_at DESC, id DESC.
 *
 * Supports optional filters: projectId, actor (principalId), action.
 * Every query carries team_id (red line 5.5). The cursor is validated
 * against the current filter set — tampered or stale cursors are rejected.
 *
 * Returns up to `limit` rows + a nextCursor (null when no more pages).
 */
export async function listAuditRecords(
  db: AppDb,
  params: ListAuditParams,
): Promise<ListAuditResult> {
  const { teamId, projectId, actor, action, cursor, limit } = params;

  const currentFilterHash = computeAuditFilterHash({
    projectId,
    actor,
    action,
  });

  // Build WHERE conditions — always scoped by team_id (red line 5.5).
  const conditions = [eq(schema.auditLog.teamId, teamId)];

  if (projectId) {
    conditions.push(
      eq(schema.auditLog.projectId, projectId),
    );
  }

  if (actor) {
    conditions.push(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      eq(schema.auditLog.principalId, actor as any),
    );
  }

  if (action) {
    conditions.push(
      eq(schema.auditLog.action, action),
    );
  }

  // Cursor: decode and apply position + validate filter hash.
  if (cursor) {
    const decoded = decodeCursor(cursor);
    if (
      decoded === null ||
      decoded.resource !== 'audit' ||
      decoded.sort !== 'created_at' ||
      decoded.filterHash !== currentFilterHash
    ) {
      throw new Error('cursor_invalid');
    }

    // Apply cursor pagination: (created_at < sortValue)
    // OR (created_at = sortValue AND id < id) — tie-breaker.
    const cursorSortValue = decoded.position.sortValue;
    const cursorId = decoded.position.id;

    conditions.push(
      or(
        lt(schema.auditLog.createdAt, new Date(cursorSortValue)),
        and(
          eq(schema.auditLog.createdAt, new Date(cursorSortValue)),
          lt(schema.auditLog.id, cursorId),
        ),
      )!,
    );
  }

  // Fetch limit + 1 to detect if there's a next page.
  const rows = await db
    .select(AUDIT_COLUMNS)
    .from(schema.auditLog)
    .where(and(...conditions))
    .orderBy(
      sql`${schema.auditLog.createdAt} DESC`,
      sql`${schema.auditLog.id} DESC`,
    )
    .limit(limit + 1);

  const hasMore = rows.length > limit;
  const resultRows = (hasMore ? rows.slice(0, limit) : rows) as unknown as AuditRow[];

  let nextCursor: string | null = null;
  if (hasMore && resultRows.length > 0) {
    const lastRow = resultRows[resultRows.length - 1]!;
    // CursorPayload requires a valid projectId (^prj_[A-Za-z0-9]+$).
    // When no projectId filter is active, use a deterministic placeholder
    // that satisfies the format requirement. Filter integrity is guaranteed
    // by filterHash — we do NOT validate projectId match on decode.
    const cursorProjectId = projectId ?? 'prj_all0000000000';
    const nextPayload: CursorPayload = {
      resource: 'audit',
      sort: 'created_at',
      v: 1,
      projectId: cursorProjectId,
      position: {
        sortValue: lastRow.createdAt.toISOString(),
        id: lastRow.id,
      },
      filterHash: currentFilterHash,
    };
    nextCursor = encodeCursor(nextPayload);
  }

  return { rows: resultRows, nextCursor };
}
